'use strict';
console.log('hello,world');
const $h1 = document.querySelector('h1');
console.log('$h1', $h1);
console.dir($h1);
const $exp = document.querySelector('#explanation');
console.log('$exp', $exp);
console.dir($exp);
const $hint = document.querySelector('.hint');
console.log('$hint', $hint);
console.dir($hint);
const $pMatches = document.querySelectorAll('p');
console.log('$pMatches', $pMatches);
const $exam = document.querySelectorAll('.example-link');
console.log('$exam', $exam);
