'use strict';
const width = 7;
const height = 14;
const area = width * height;
console.log('Value of Area: ', area);
console.log('Type of Area: ', typeof area);
const bill = 30;
const payment = 50;
const change = payment - bill;
console.log('Value of change: ', change);
console.log('Type of Change: ', typeof change);
const quizzes = 5;
const midterm = 10;
const final = 15;
const grade = (quizzes + midterm + final) / 3;
console.log('Value of grade: ', grade);
console.log('Type of Grade: ', grade);
const firstName = 'Victoria';
const lastName = 'Dixon';
const fullName = firstName + ' ' + lastName;
console.log('Value of Full Name: ', fullName);
console.log('Type of Full Name: ', fullName);
const pH = 4;
const isAcidic = pH < 7;
console.log('Value of isAcidic: ', isAcidic);
console.log('Type of isAcidic: ', typeof isAcidic);
const headCount = 100;
const isSparta = headCount === 300;
console.log('Value of isSparta: ', isSparta);
console.log('Type of isSparta ', typeof isSparta);
const motto = fullName + ' ' + 'is the GOAT';
console.log('Value of motto: ', motto);
console.log('Type of Motto: ', typeof motto);
